CREATE TABLE IF NOT EXISTS product (
    name VARCHAR PRIMARY KEY,
    description VARCHAR
);

CREATE TABLE IF NOT EXISTS store (
    id INTEGER PRIMARY KEY,
    city VARCHAR
);

CREATE TABLE IF NOT EXISTS time (
    id INTEGER PRIMARY KEY,
    day INTEGER ,
    month INTEGER,
    year INTEGER
);