version: "3.1"
services:
  postgres:
    image: "postgres"
    hostname: postgres
    container_name: postgres_database
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
    #   POSTGRES_USER: user
      POSTGRES_PASSWORD: password