version: "3.1"
services:
  postgres:
    image: "postgres"
    container_name: starschema_demo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password