version: "3.1"
services:
  postgres:
    image: "postgres"
    # hostname: postgres
    # container_name: postgres_database
    # network_mode: bridge
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    # environment:
    #   - POSTGRES_USER=root
    #   - POSTGRES_PASSWORD=password
    volumes:
      - ./create-databases.sql:/docker-entrypoint-initdb.d/01-create-databases.sql
      - ./create-databases.sh:/docker-entrypoint-initdb.d/02-create-databases.sh
      - ./relational-database.create:/docker-entrypoint-initdb.d/relational-database.create
      - ./star-database.create:/docker-entrypoint-initdb.d/star-database.create