version: "3.1"
services:
  postgres:
    image: "postgres"
    # hostname: postgres
    # container_name: postgres_database
    # network_mode: bridge
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql